name: Town Planner CLE
favicon: null
layout_spectrum: 0.753153987461701
typography_spectrum: 0.18533618072979152
title: Town Planner CLE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#eee63b'
    - '#252f74'
    - '#428045'
    - '#c3c8d5'
  brandStrength: 0.7657354117836803
  lightness: 0.5
  saturation: 0.625
  rhythmicContrast: 0.25
purpose: []
