name: Town Planner CLE
favicon: null
layout_spectrum: 0.31722
typography_spectrum: 0.18533618072979152
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B0C8D0'
    - '#802020'
    - '#908060'
    - '#E8B020'
    - '#D0E0F0'
  brandStrength: 0.765735
  lightness: 0.5
  saturation: 0.339527
  rhythmicContrast: 0.25
purpose: []
