analytics: {}
color:
  brandColors:
    - '#B0C8D0'
    - '#802020'
    - '#908060'
    - '#E8B020'
    - '#D0E0F0'
  brandStrength: 0.765735
  lightness: 0.5
  rhythmicContrast: 0.25
  saturation: 0.339527
cta: {}
layout_spectrum: 0.399493
name: Town Planner CLE
opengraph: {}
purpose: []
typography_spectrum: 0.18533618072979152
