name: Town Planner CLE
favicon: null
layout_spectrum: 0.753153987461701
typography_spectrum: 0.18533618072979152
title: Town Planner CLE
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#d7e1ea'
    - '#000000'
    - '#9c9c9c'
    - '#6f422f'
    - '#f26453'
  brandStrength: 0.7657354117836803
  lightness: 0.19555389671586454
  saturation: 0.8217802273575217
  rhythmicContrast: 0.69930828968063
purpose: []
